spring.application.name=ecommerce

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15432/ecommerce}
spring.datasource.username=${DB_USERNAME:ecommerce}
spring.datasource.password=${DB_PASSWORD:ecommerce}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
